language: php

php:
  - 7.2
  - 7.3

sudo: false

install:
  - travis_retry composer install

script:
  - composer validate --no-interaction
  - ./vendor/bin/covers-validator
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs -p -s
  - ./vendor/bin/phpstan analyse --level=1 --no-progress src/ tests/

after_success:
  - if [[ "`phpenv version-name`" != "7.3" ]]; then exit 0; fi
  - vendor/bin/phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
